In [4]:
import pandas as pd

In [3]:
path = '/content/LOG_20210101_001253_025162(藤井寺IC)_L5.xlsx'
data = pd.ExcelFile(path)
sheets = data.sheet_names
df = pd.DataFrame()
for s in sheets[:]:
  tmp = data.parse(s, skiprows=[0, 1, 2, 3, 4, 5], index_col=0)
  df = pd.concat([df, tmp])

In [25]:
df.reset_index(drop=True, inplace=True)

In [32]:
# 7040910
idx_v = (df[df['ETC\n一連番号'] == 7040910].index[0], df[df['ETC\n一連番号'] == 7040910].index[-1])
df_v = df.iloc[idx_v[0]: idx_v[1]+1, :]
df_v.reset_index(drop=True, inplace=True)
df_v

,日時,ETC\n一連番号,S1～S4,S1～S2,S2～S4,S1,S1前進進入,S1前進退出,S2,S4,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,2020/12/31 23:12:30.265,7040910.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),Ｓ１進入カウンタ値：1971/01/24 21:15:47773.441.236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020/12/31 23:12:30.266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,第１・リカバリアンテナ通信開始通知,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020/12/31 23:12:30.266,7040910.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),処理時刻：2020/12/31 23:12:30,通信一連番号：006BAE3C(7056956),アンテナ：第１,車判情報：接続なし,強制流出：通常,縮退運転：通常,NaN,NaN,NaN
3,2020/12/31 23:12:30.266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＮＰ：0000000000000000,軸計測：未確定,車種計測：なし／未確定,車高計測：正常,交通量調査：なし,調査開始：1997/00/00 00:00:00,調査終了：1997/00/00 00:00:00,NaN,NaN,NaN
4,2020/12/31 23:12:30.266,7040910.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),車検Ｓ１進入,対象,０軸,車高：未検知,軸重：未検知,スロット番号：0000001A(26),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2020/12/31 23:12:33.970,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),割引後通行料金：\0,課金有無：課金あり,セットアップ車種：普通,課金車種：普通,牽引：なし,割引ＩＤ：34,乗直：なし,読込－処理結果：0x01,読込－決済結果：0x80
122,2020/12/31 23:12:33.970,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,処理結果：0x00（正常）,決済結果：0x80（未精算：道路内）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,2020/12/31 23:12:33.970,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,一致,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,2020/12/31 23:12:33.970,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),正常ＥＴＣ車,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,2020/12/31 23:12:34.353,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),車検Ｓ４退出,対象,０軸,車高：未検知,軸重：未検知,スロット番号：0000001A(26),NaN,NaN,NaN

In [38]:
idx = (df_v[df_v['全イベント'] == '車検変化'].index[0], df_v[df_v['全イベント'] == '車検変化'].index[-1])
# print(idx)
df_v2 = df_v.iloc[idx[0]: idx[1]+1, :]
df_v2.reset_index(drop=True, inplace=True)
df_v2

,日時,ETC\n一連番号,S1～S4,S1～S2,S2～S4,S1,S1前進進入,S1前進退出,S2,S4,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,2020/12/31 23:12:30.266,7040910.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),車検Ｓ１進入,対象,０軸,車高：未検知,軸重：未検知,スロット番号：0000001A(26),NaN,NaN,NaN
1,2020/12/31 23:12:30.267,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,台数（Ｓ１－Ｓ４）1台,台数（Ｓ１－Ｓ２）1台,台数（Ｓ２－Ｓ４）0台,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020/12/31 23:12:30.268,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,レングス：44,車両検知情報,伝送連番：15723,車両管理番号：0x006B6F8E,処理時刻：2020/12/31 23:12:30 00,運用モード：0x01,送信区分：0x01,NaN,NaN,NaN
3,2020/12/31 23:12:30.270,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,車両データ,ＥＴＣ一連番号：0x00000000(0),その他（0x00）,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020/12/31 23:12:30.272,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,結果：消灯,待機消灯,故障ブザー停止,強制開消灯,台数：１台,車両ブザー：停止,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,2020/12/31 23:12:33.970,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),割引後通行料金：\0,課金有無：課金あり,セットアップ車種：普通,課金車種：普通,牽引：なし,割引ＩＤ：34,乗直：なし,読込－処理結果：0x01,読込－決済結果：0x80
118,2020/12/31 23:12:33.970,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,処理結果：0x00（正常）,決済結果：0x80（未精算：道路内）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,2020/12/31 23:12:33.970,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,一致,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,2020/12/31 23:12:33.970,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),正常ＥＴＣ車,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,2020/12/31 23:12:34.353,7040910.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ＥＴＣ処理一連番号：006B6F8E(7040910),車検Ｓ４退出,対象,０軸,車高：未検知,軸重：未検知,スロット番号：0000001A(26),NaN,NaN,NaN

In [110]:
cols = ['全イベント', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46',
       'Unnamed: 47']
df_v2[cols]

,全イベント,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,車検変化,ＥＴＣ処理一連番号：006B6F8E(7040910),車検Ｓ１進入,対象,０軸,車高：未検知,軸重：未検知,スロット番号：0000001A(26),NaN,NaN,NaN
1,車両台数,台数（Ｓ１－Ｓ４）1台,台数（Ｓ１－Ｓ２）1台,台数（Ｓ２－Ｓ４）0台,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,走行車両重量測定装置送信,レングス：44,車両検知情報,伝送連番：15723,車両管理番号：0x006B6F8E,処理時刻：2020/12/31 23:12:30 00,運用モード：0x01,送信区分：0x01,NaN,NaN,NaN
3,車監装送信,車両データ,ＥＴＣ一連番号：0x00000000(0),その他（0x00）,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ブース内表示器 出力,結果：消灯,待機消灯,故障ブザー停止,強制開消灯,台数：１台,車両ブザー：停止,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
117,第２アンテナ通信結果－路線Ａ,ＥＴＣ処理一連番号：006B6F8E(7040910),割引後通行料金：\0,課金有無：課金あり,セットアップ車種：普通,課金車種：普通,牽引：なし,割引ＩＤ：34,乗直：なし,読込－処理結果：0x01,読込－決済結果：0x80
118,第２アンテナ通信結果－路線Ａ（続き）,処理結果：0x00（正常）,決済結果：0x80（未精算：道路内）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,出口情報比較結果,一致,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,判定結果,ＥＴＣ処理一連番号：006B6F8E(7040910),正常ＥＴＣ車,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,車検変化,ＥＴＣ処理一連番号：006B6F8E(7040910),車検Ｓ４退出,対象,０軸,車高：未検知,軸重：未検知,スロット番号：0000001A(26),NaN,NaN,NaN

In [126]:
sub_df_v2 = df_v2[df_v2['全イベント']=='車検変化']
sub_df_v2.reset_index(drop=True, inplace=True)
sub_v2 = {'nodes': [], 'combos': [], 'edges': []}
sub_v2['combos'].append({'id': 'n.車検変化', 'label': '車検変化'})
for i in sub_df_v2['Unnamed: 39'].value_counts().index.tolist():
  sub_v2['nodes'].append({'id': i, 'label': i, 'comboId': 'n.車検変化'})
for i in range(len(sub_df_v2)-1):
  # print(i)
  # print(sub_df_v2.loc[i, 'Unnamed: 39'], sub_df_v2.loc[i+1, 'Unnamed: 39'])
  sub_v2['edges'].append({'source': sub_df_v2.loc[i, 'Unnamed: 39'], 'target': sub_df_v2.loc[i+1, 'Unnamed: 39']})

In [128]:
import json
with open('data-sub-v3.1.json', 'wb') as fp:
    fp.write(json.dumps(sub_v2, ensure_ascii=False).encode("utf8"))

In [102]:
df_v2['combo'] = ''
key_words = ['ＮＰ読取', '軸検知', '不正防止', '料金所サ', 'ＥＴＣ処理', '第１アンテナ', 'ＤＳＲＣ通信', \
                '第２アンテナ', '車検変化', 'Ｓ１割込み', '路側表示', '車監装', '発進制御', '簡易操作', \
                    '車載器指示', '車両台数', '重量測定装置']
reject_combo = []
for k in key_words:
  row_indexer = df_v2[df_v2['全イベント'].str.contains(k)].index
  if len(row_indexer) == 0:
    reject_combo.append(k)
  df_v2.loc[row_indexer, 'combo'] = 'c.'+k

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [105]:
v2 = {'nodes': [], 'combos': [], 'edges': []}
for i, label in enumerate([i for i in key_words if i not in reject_combo]):
  v2['combos'].append({'id': 'c.'+ label, 'label': label})

In [104]:
v2['combos']

[{'id': 'c.軸検知', 'label': '軸検知'},
 {'id': 'c.不正防止', 'label': '不正防止'},
 {'id': 'c.ＥＴＣ処理', 'label': 'ＥＴＣ処理'},
 {'id': 'c.第１アンテナ', 'label': '第１アンテナ'},
 {'id': 'c.ＤＳＲＣ通信', 'label': 'ＤＳＲＣ通信'},
 {'id': 'c.第２アンテナ', 'label': '第２アンテナ'},
 {'id': 'c.車検変化', 'label': '車検変化'},
 {'id': 'c.Ｓ１割込み', 'label': 'Ｓ１割込み'},
 {'id': 'c.路側表示', 'label': '路側表示'},
 {'id': 'c.車監装', 'label': '車監装'},
 {'id': 'c.発進制御', 'label': '発進制御'},
 {'id': 'c.簡易操作', 'label': '簡易操作'},
 {'id': 'c.車両台数', 'label': '車両台数'},
 {'id': 'c.重量測定装置', 'label': '重量測定装置'}]

In [107]:
# v2['nodes'].append({'id': 'n.start', 'label': 'start'})
# v2['nodes'].append({'id': 'n.end', 'label': 'end'})
# for i in df_v2[['全イベント', 'combo']].value_counts().index.tolist():
#   v2['nodes'].append({'id': 'n.'+i[0], 'label': i[0], 'comboId': i[1]})
# v2['edges'].append({'source': 'n.start', 'target': 'n.'+df_v2.loc[0, '全イベント']})
# for i in range(len(df_v2)-1):
#   if df_v2.loc[i, '全イベント'] == '車検変化':
#     v2['edges'].append({'source': 'n.'+df_v2.loc[i, '全イベント'], 'target': 'n.'+df_v2.loc[i+1, '全イベント'], 'label': df_v2.loc[i, 'Unnamed: 39']})
#   else:
#     v2['edges'].append({'source': 'n.'+df_v2.loc[i, '全イベント'], 'target': 'n.'+df_v2.loc[i+1, '全イベント']})
# v2['edges'].append({'source': 'n.'+df_v2.loc[i+1, '全イベント'], 'target': 'n.end'})

v2['combos'].append({'id': 'c.c.start', 'label': 'start'})
v2['combos'].append({'id': 'c.c.end', 'label': 'end'})
for i in df_v2[['全イベント', 'combo']].value_counts().index.tolist():
  v2['combos'].append({'id': 'c.c.'+i[0], 'label': i[0], 'parentId': i[1]})
v2['edges'].append({'source': 'c.c.start', 'target': 'c.c.'+df_v2.loc[0, '全イベント']})
for i in range(len(df_v2)-1):
  if df_v2.loc[i, '全イベント'] == '車検変化':
    v2['edges'].append({'source': 'c.c.'+df_v2.loc[i, '全イベント'], 'target': 'c.c.'+df_v2.loc[i+1, '全イベント'], 'label': df_v2.loc[i, 'Unnamed: 39']})
  else:
    v2['edges'].append({'source': 'c.c.'+df_v2.loc[i, '全イベント'], 'target': 'c.c.'+df_v2.loc[i+1, '全イベント']})
v2['edges'].append({'source': 'c.c.'+df_v2.loc[i+1, '全イベント'], 'target': 'c.c.end'})

In [109]:
import json
with open('data-v3.1.json', 'wb') as fp:
    fp.write(json.dumps(v2, ensure_ascii=False).encode("utf8"))